CREATE TABLE PRODUCT
(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CATEGORY_ID INTEGER NOT NULL
);

CREATE TABLE CATEGORY
(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME VARCHAR(100) NOT NULL
);
